# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.KMC_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.KMC_GroupBox.setGeometry(QtCore.QRect(10, 60, 461, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.KMC_GroupBox.setFont(font)
        self.KMC_GroupBox.setObjectName("KMC_GroupBox")
        self.Samples_FASTAQ_Path_Edit = QtWidgets.QLineEdit(self.KMC_GroupBox)
        self.Samples_FASTAQ_Path_Edit.setGeometry(QtCore.QRect(220, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Samples_FASTAQ_Path_Edit.setFont(font)
        self.Samples_FASTAQ_Path_Edit.setReadOnly(True)
        self.Samples_FASTAQ_Path_Edit.setObjectName("Samples_FASTAQ_Path_Edit")
        self.Open_Samples_FASTAQ_Button = QtWidgets.QPushButton(self.KMC_GroupBox)
        self.Open_Samples_FASTAQ_Button.setGeometry(QtCore.QRect(400, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Open_Samples_FASTAQ_Button.setFont(font)
        self.Open_Samples_FASTAQ_Button.setObjectName("Open_Samples_FASTAQ_Button")
        self.KMC_Project_Status_Label = QtWidgets.QLabel(self.KMC_GroupBox)
        self.KMC_Project_Status_Label.setGeometry(QtCore.QRect(10, 25, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.KMC_Project_Status_Label.setFont(font)
        self.KMC_Project_Status_Label.setObjectName("KMC_Project_Status_Label")
        self.Samples_Path_Label = QtWidgets.QLabel(self.KMC_GroupBox)
        self.Samples_Path_Label.setGeometry(QtCore.QRect(10, 50, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Samples_Path_Label.setFont(font)
        self.Samples_Path_Label.setObjectName("Samples_Path_Label")
        self.KMC_GO_Button = QtWidgets.QPushButton(self.KMC_GroupBox)
        self.KMC_GO_Button.setGeometry(QtCore.QRect(350, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.KMC_GO_Button.setFont(font)
        self.KMC_GO_Button.setObjectName("KMC_GO_Button")
        self.K_Value_Label = QtWidgets.QLabel(self.KMC_GroupBox)
        self.K_Value_Label.setGeometry(QtCore.QRect(10, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.K_Value_Label.setFont(font)
        self.K_Value_Label.setObjectName("K_Value_Label")
        self.K_Value_Edit = QtWidgets.QLineEdit(self.KMC_GroupBox)
        self.K_Value_Edit.setGeometry(QtCore.QRect(40, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.K_Value_Edit.setFont(font)
        self.K_Value_Edit.setObjectName("K_Value_Edit")
        self.CiValue_Label = QtWidgets.QLabel(self.KMC_GroupBox)
        self.CiValue_Label.setGeometry(QtCore.QRect(80, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.CiValue_Label.setFont(font)
        self.CiValue_Label.setObjectName("CiValue_Label")
        self.CI_Value_Edit = QtWidgets.QLineEdit(self.KMC_GroupBox)
        self.CI_Value_Edit.setGeometry(QtCore.QRect(160, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CI_Value_Edit.setFont(font)
        self.CI_Value_Edit.setObjectName("CI_Value_Edit")
        self.CsValue_Label = QtWidgets.QLabel(self.KMC_GroupBox)
        self.CsValue_Label.setGeometry(QtCore.QRect(200, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.CsValue_Label.setFont(font)
        self.CsValue_Label.setObjectName("CsValue_Label")
        self.CS_Value_Edit = QtWidgets.QLineEdit(self.KMC_GroupBox)
        self.CS_Value_Edit.setGeometry(QtCore.QRect(280, 80, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_Value_Edit.setFont(font)
        self.CS_Value_Edit.setObjectName("CS_Value_Edit")
        self.GM_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.GM_GroupBox.setGeometry(QtCore.QRect(10, 180, 461, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.GM_GroupBox.setFont(font)
        self.GM_GroupBox.setObjectName("GM_GroupBox")
        self.GM_Project_Status_Label = QtWidgets.QLabel(self.GM_GroupBox)
        self.GM_Project_Status_Label.setGeometry(QtCore.QRect(10, 25, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.GM_Project_Status_Label.setFont(font)
        self.GM_Project_Status_Label.setObjectName("GM_Project_Status_Label")
        self.KMC_Result_Path_Label = QtWidgets.QLabel(self.GM_GroupBox)
        self.KMC_Result_Path_Label.setGeometry(QtCore.QRect(10, 50, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.KMC_Result_Path_Label.setFont(font)
        self.KMC_Result_Path_Label.setObjectName("KMC_Result_Path_Label")
        self.KMC_Result_Path_Edit = QtWidgets.QLineEdit(self.GM_GroupBox)
        self.KMC_Result_Path_Edit.setGeometry(QtCore.QRect(220, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.KMC_Result_Path_Edit.setFont(font)
        self.KMC_Result_Path_Edit.setReadOnly(True)
        self.KMC_Result_Path_Edit.setObjectName("KMC_Result_Path_Edit")
        self.KMC_Result_Path_Button = QtWidgets.QPushButton(self.GM_GroupBox)
        self.KMC_Result_Path_Button.setGeometry(QtCore.QRect(400, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.KMC_Result_Path_Button.setFont(font)
        self.KMC_Result_Path_Button.setObjectName("KMC_Result_Path_Button")
        self.Process_Number_Label = QtWidgets.QLabel(self.GM_GroupBox)
        self.Process_Number_Label.setGeometry(QtCore.QRect(10, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Process_Number_Label.setFont(font)
        self.Process_Number_Label.setObjectName("Process_Number_Label")
        self.Process_Number_Edit = QtWidgets.QLineEdit(self.GM_GroupBox)
        self.Process_Number_Edit.setGeometry(QtCore.QRect(180, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Process_Number_Edit.setFont(font)
        self.Process_Number_Edit.setObjectName("Process_Number_Edit")
        self.GM_GO_Button = QtWidgets.QPushButton(self.GM_GroupBox)
        self.GM_GO_Button.setGeometry(QtCore.QRect(350, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GM_GO_Button.setFont(font)
        self.GM_GO_Button.setObjectName("GM_GO_Button")
        self.GF_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.GF_GroupBox.setGeometry(QtCore.QRect(10, 300, 461, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.GF_GroupBox.setFont(font)
        self.GF_GroupBox.setObjectName("GF_GroupBox")
        self.GF_Project_Status_Label = QtWidgets.QLabel(self.GF_GroupBox)
        self.GF_Project_Status_Label.setGeometry(QtCore.QRect(10, 25, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.GF_Project_Status_Label.setFont(font)
        self.GF_Project_Status_Label.setObjectName("GF_Project_Status_Label")
        self.GM_Result_Path_Label = QtWidgets.QLabel(self.GF_GroupBox)
        self.GM_Result_Path_Label.setGeometry(QtCore.QRect(10, 50, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.GM_Result_Path_Label.setFont(font)
        self.GM_Result_Path_Label.setObjectName("GM_Result_Path_Label")
        self.GM_Result_Path_Edit = QtWidgets.QLineEdit(self.GF_GroupBox)
        self.GM_Result_Path_Edit.setGeometry(QtCore.QRect(220, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GM_Result_Path_Edit.setFont(font)
        self.GM_Result_Path_Edit.setReadOnly(True)
        self.GM_Result_Path_Edit.setObjectName("GM_Result_Path_Edit")
        self.GM_Result_Path_Button = QtWidgets.QPushButton(self.GF_GroupBox)
        self.GM_Result_Path_Button.setGeometry(QtCore.QRect(400, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GM_Result_Path_Button.setFont(font)
        self.GM_Result_Path_Button.setObjectName("GM_Result_Path_Button")
        self.ASS_l_Value_Label = QtWidgets.QLabel(self.GF_GroupBox)
        self.ASS_l_Value_Label.setGeometry(QtCore.QRect(0, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ASS_l_Value_Label.setFont(font)
        self.ASS_l_Value_Label.setObjectName("ASS_l_Value_Label")
        self.ASS_l_Value_Edit = QtWidgets.QLineEdit(self.GF_GroupBox)
        self.ASS_l_Value_Edit.setGeometry(QtCore.QRect(70, 140, 51, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ASS_l_Value_Edit.setFont(font)
        self.ASS_l_Value_Edit.setObjectName("ASS_l_Value_Edit")
        self.P_Value_Label = QtWidgets.QLabel(self.GF_GroupBox)
        self.P_Value_Label.setGeometry(QtCore.QRect(120, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.P_Value_Label.setFont(font)
        self.P_Value_Label.setObjectName("P_Value_Label")
        self.P_Value_Edit = QtWidgets.QLineEdit(self.GF_GroupBox)
        self.P_Value_Edit.setGeometry(QtCore.QRect(160, 140, 61, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.P_Value_Edit.setFont(font)
        self.P_Value_Edit.setObjectName("P_Value_Edit")
        self.ASS_n_Value_Label = QtWidgets.QLabel(self.GF_GroupBox)
        self.ASS_n_Value_Label.setGeometry(QtCore.QRect(220, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ASS_n_Value_Label.setFont(font)
        self.ASS_n_Value_Label.setObjectName("ASS_n_Value_Label")
        self.ASS_n_Value_Edit = QtWidgets.QLineEdit(self.GF_GroupBox)
        self.ASS_n_Value_Edit.setGeometry(QtCore.QRect(290, 140, 51, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ASS_n_Value_Edit.setFont(font)
        self.ASS_n_Value_Edit.setObjectName("ASS_n_Value_Edit")
        self.GF_GO_Button = QtWidgets.QPushButton(self.GF_GroupBox)
        self.GF_GO_Button.setGeometry(QtCore.QRect(350, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GF_GO_Button.setFont(font)
        self.GF_GO_Button.setObjectName("GF_GO_Button")
        self.Trait_Info_Path_Label = QtWidgets.QLabel(self.GF_GroupBox)
        self.Trait_Info_Path_Label.setGeometry(QtCore.QRect(10, 80, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Trait_Info_Path_Label.setFont(font)
        self.Trait_Info_Path_Label.setObjectName("Trait_Info_Path_Label")
        self.Trait_Info_Path_Edit = QtWidgets.QLineEdit(self.GF_GroupBox)
        self.Trait_Info_Path_Edit.setGeometry(QtCore.QRect(220, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Trait_Info_Path_Edit.setFont(font)
        self.Trait_Info_Path_Edit.setReadOnly(True)
        self.Trait_Info_Path_Edit.setObjectName("Trait_Info_Path_Edit")
        self.Trait_Info_Path_Button = QtWidgets.QPushButton(self.GF_GroupBox)
        self.Trait_Info_Path_Button.setGeometry(QtCore.QRect(400, 80, 51, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Trait_Info_Path_Button.setFont(font)
        self.Trait_Info_Path_Button.setObjectName("Trait_Info_Path_Button")
        self.Catagorical_RadioButton = QtWidgets.QRadioButton(self.GF_GroupBox)
        self.Catagorical_RadioButton.setGeometry(QtCore.QRect(60, 110, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Catagorical_RadioButton.setFont(font)
        self.Catagorical_RadioButton.setChecked(True)
        self.Catagorical_RadioButton.setObjectName("Catagorical_RadioButton")
        self.Continuous_RadioButton = QtWidgets.QRadioButton(self.GF_GroupBox)
        self.Continuous_RadioButton.setGeometry(QtCore.QRect(270, 110, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Continuous_RadioButton.setFont(font)
        self.Continuous_RadioButton.setChecked(False)
        self.Continuous_RadioButton.setObjectName("Continuous_RadioButton")
        self.KA_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.KA_GroupBox.setGeometry(QtCore.QRect(10, 480, 461, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.KA_GroupBox.setFont(font)
        self.KA_GroupBox.setObjectName("KA_GroupBox")
        self.KA_Project_Status_Label = QtWidgets.QLabel(self.KA_GroupBox)
        self.KA_Project_Status_Label.setGeometry(QtCore.QRect(10, 25, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.KA_Project_Status_Label.setFont(font)
        self.KA_Project_Status_Label.setObjectName("KA_Project_Status_Label")
        self.GF_Result_Path_Label = QtWidgets.QLabel(self.KA_GroupBox)
        self.GF_Result_Path_Label.setGeometry(QtCore.QRect(10, 50, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.GF_Result_Path_Label.setFont(font)
        self.GF_Result_Path_Label.setObjectName("GF_Result_Path_Label")
        self.GF_Result_Path_Button = QtWidgets.QPushButton(self.KA_GroupBox)
        self.GF_Result_Path_Button.setGeometry(QtCore.QRect(400, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GF_Result_Path_Button.setFont(font)
        self.GF_Result_Path_Button.setObjectName("GF_Result_Path_Button")
        self.GF_Result_Path_Edit = QtWidgets.QLineEdit(self.KA_GroupBox)
        self.GF_Result_Path_Edit.setGeometry(QtCore.QRect(220, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GF_Result_Path_Edit.setFont(font)
        self.GF_Result_Path_Edit.setReadOnly(True)
        self.GF_Result_Path_Edit.setObjectName("GF_Result_Path_Edit")
        self.KA_GO_Button = QtWidgets.QPushButton(self.KA_GroupBox)
        self.KA_GO_Button.setGeometry(QtCore.QRect(350, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.KA_GO_Button.setFont(font)
        self.KA_GO_Button.setObjectName("KA_GO_Button")
        self.OneClickRunningButton = QtWidgets.QPushButton(self.centralwidget)
        self.OneClickRunningButton.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OneClickRunningButton.setFont(font)
        self.OneClickRunningButton.setObjectName("OneClickRunningButton")
        self.StepByStepRunningButton = QtWidgets.QPushButton(self.centralwidget)
        self.StepByStepRunningButton.setGeometry(QtCore.QRect(240, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.StepByStepRunningButton.setFont(font)
        self.StepByStepRunningButton.setObjectName("StepByStepRunningButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.NewProject_Action = QtWidgets.QAction(MainWindow)
        self.NewProject_Action.setObjectName("NewProject_Action")
        self.OpenProject_Action = QtWidgets.QAction(MainWindow)
        self.OpenProject_Action.setObjectName("OpenProject_Action")
        self.SaveProject_Action = QtWidgets.QAction(MainWindow)
        self.SaveProject_Action.setObjectName("SaveProject_Action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.OneClickRunningButton, self.StepByStepRunningButton)
        MainWindow.setTabOrder(self.StepByStepRunningButton, self.Samples_FASTAQ_Path_Edit)
        MainWindow.setTabOrder(self.Samples_FASTAQ_Path_Edit, self.Open_Samples_FASTAQ_Button)
        MainWindow.setTabOrder(self.Open_Samples_FASTAQ_Button, self.K_Value_Edit)
        MainWindow.setTabOrder(self.K_Value_Edit, self.CI_Value_Edit)
        MainWindow.setTabOrder(self.CI_Value_Edit, self.CS_Value_Edit)
        MainWindow.setTabOrder(self.CS_Value_Edit, self.KMC_GO_Button)
        MainWindow.setTabOrder(self.KMC_GO_Button, self.KMC_Result_Path_Edit)
        MainWindow.setTabOrder(self.KMC_Result_Path_Edit, self.KMC_Result_Path_Button)
        MainWindow.setTabOrder(self.KMC_Result_Path_Button, self.Process_Number_Edit)
        MainWindow.setTabOrder(self.Process_Number_Edit, self.GM_GO_Button)
        MainWindow.setTabOrder(self.GM_GO_Button, self.GM_Result_Path_Edit)
        MainWindow.setTabOrder(self.GM_Result_Path_Edit, self.GM_Result_Path_Button)
        MainWindow.setTabOrder(self.GM_Result_Path_Button, self.Trait_Info_Path_Edit)
        MainWindow.setTabOrder(self.Trait_Info_Path_Edit, self.Trait_Info_Path_Button)
        MainWindow.setTabOrder(self.Trait_Info_Path_Button, self.Catagorical_RadioButton)
        MainWindow.setTabOrder(self.Catagorical_RadioButton, self.Continuous_RadioButton)
        MainWindow.setTabOrder(self.Continuous_RadioButton, self.ASS_l_Value_Edit)
        MainWindow.setTabOrder(self.ASS_l_Value_Edit, self.P_Value_Edit)
        MainWindow.setTabOrder(self.P_Value_Edit, self.ASS_n_Value_Edit)
        MainWindow.setTabOrder(self.ASS_n_Value_Edit, self.GF_GO_Button)
        MainWindow.setTabOrder(self.GF_GO_Button, self.GF_Result_Path_Edit)
        MainWindow.setTabOrder(self.GF_Result_Path_Edit, self.GF_Result_Path_Button)
        MainWindow.setTabOrder(self.GF_Result_Path_Button, self.KA_GO_Button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.KMC_GroupBox.setTitle(_translate("MainWindow", "K-mer counting"))
        self.Open_Samples_FASTAQ_Button.setText(_translate("MainWindow", "Select"))
        self.KMC_Project_Status_Label.setText(_translate("MainWindow", "Status:"))
        self.Samples_Path_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">FASTA/Q files path of samples</p></body></html>"))
        self.KMC_GO_Button.setText(_translate("MainWindow", "Start"))
        self.K_Value_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">K =</p></body></html>"))
        self.K_Value_Edit.setText(_translate("MainWindow", "40"))
        self.CiValue_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">MinValue =</p></body></html>"))
        self.CI_Value_Edit.setText(_translate("MainWindow", "2"))
        self.CsValue_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">MaxValue =</p></body></html>"))
        self.CS_Value_Edit.setText(_translate("MainWindow", "65536"))
        self.GM_GroupBox.setTitle(_translate("MainWindow", "K-mer counting union matrix"))
        self.GM_Project_Status_Label.setText(_translate("MainWindow", "Status:"))
        self.KMC_Result_Path_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">K-mer counting files path</p></body></html>"))
        self.KMC_Result_Path_Button.setText(_translate("MainWindow", "Select"))
        self.Process_Number_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Number of processes =</p></body></html>"))
        self.Process_Number_Edit.setText(_translate("MainWindow", "24"))
        self.GM_GO_Button.setText(_translate("MainWindow", "Start"))
        self.GF_GroupBox.setTitle(_translate("MainWindow", "K-mer features filtering"))
        self.GF_Project_Status_Label.setText(_translate("MainWindow", "Status:"))
        self.GM_Result_Path_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">KMC matrix files path</p></body></html>"))
        self.GM_Result_Path_Button.setText(_translate("MainWindow", "Select"))
        self.ASS_l_Value_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ASS-l =</p></body></html>"))
        self.ASS_l_Value_Edit.setText(_translate("MainWindow", "0.80"))
        self.P_Value_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">p =</p></body></html>"))
        self.P_Value_Edit.setText(_translate("MainWindow", "0.01"))
        self.ASS_n_Value_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ASS-n =</p></body></html>"))
        self.ASS_n_Value_Edit.setText(_translate("MainWindow", "0.80"))
        self.GF_GO_Button.setText(_translate("MainWindow", "Start"))
        self.Trait_Info_Path_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">A CSV file of trait information</p></body></html>"))
        self.Trait_Info_Path_Button.setText(_translate("MainWindow", "Select"))
        self.Catagorical_RadioButton.setText(_translate("MainWindow", "Catagorical Trait"))
        self.Continuous_RadioButton.setText(_translate("MainWindow", "Continuous Trait"))
        self.KA_GroupBox.setTitle(_translate("MainWindow", "K-mers assembly"))
        self.KA_Project_Status_Label.setText(_translate("MainWindow", "Status:"))
        self.GF_Result_Path_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">K-mer feature files path</p></body></html>"))
        self.GF_Result_Path_Button.setText(_translate("MainWindow", "Select"))
        self.KA_GO_Button.setText(_translate("MainWindow", "Start"))
        self.OneClickRunningButton.setText(_translate("MainWindow", "One Click Running"))
        self.StepByStepRunningButton.setText(_translate("MainWindow", "*Step By Step Running"))
        self.NewProject_Action.setText(_translate("MainWindow", "新建项目"))
        self.OpenProject_Action.setText(_translate("MainWindow", "打开项目"))
        self.SaveProject_Action.setText(_translate("MainWindow", "保存项目"))
